name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day
  workflow_dispatch:      # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: what-the-twink
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
